name: silverpurple
description: Custom Fedora Silverblue image

base-image: quay.io/fedora/fedora-silverblue
image-version: 43

modules:
  - type: rpm-ostree
    repos:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    remove:
      - firefox
      - firefox-langpacks
      - ffmpeg-free
      - libavcodec-free
      - libavdevice-free
      - libavfilter-free
      - libavformat-free
      - libavutil-free
      - libpostproc-free
      - libswresample-free
      - libswscale-free
      - mesa-va-drivers
    install:
      # Codecs and drivers
      - ffmpeg
      - ffmpegthumbnailer
      - mesa-va-drivers-freeworld
      - mesa-vdpau-drivers-freeworld
      - pipewire-codec-aptx
      # Fonts
      - google-noto-fonts-all-vf
      # Terminal tools
      - alacritty
      - fish
      - tmux
      - bat
      - lsd
      # Dev tools
      - java-latest-openjdk
      - nmap
      - tcpdump
      # Services
      - mullvad-vpn
      - nebula
      - syncthing
      - waydroid

  - type: default-flatpaks
    system:
      repo-url: ""
      repo-name: ""
      repo-title: ""
      install: []
      remove:
        - fedora
