name: silverpurple
description: A custom Silverblue image with stuff you actually need

base-image: ghcr.io/myyc/silverpurple-base
image-version: latest

modules:
  - type: signing
  - from-file: common.yml
